@extends('layouts.app')

@section('content')
<section class="border-b border-stone-200 bg-white">
    <div class="section grid items-center gap-10 py-16 md:py-20 lg:grid-cols-[1.05fr_1fr] lg:gap-14">
        <div>
            <h1 class="display-serif text-5xl leading-[1.05] md:text-6xl">One daily product.<br>A few guided moments.<br>A clearer decision at Day 30.</h1>
            <p class="mt-6 max-w-md text-[15px] leading-7 text-stone-600">The 30-day guided course records enough about your daily routine and reported response to make the end read honest.</p>
            <div class="mt-7 flex flex-wrap gap-3"><a href="{{ route('shop') }}" class="btn-primary">View Product</a><a href="{{ url('/#standards') }}" class="btn-secondary">Review Standards</a></div>
        </div>
        <div class="overflow-hidden rounded-xl bg-[var(--cream)]"><img src="https://guided-gut-reset-lovable-app.lovable.app/assets/hero-product-CftTmpl1.jpg" alt="Morning product routine" class="aspect-[4/3] h-full w-full object-cover"></div>
    </div>
</section>

<section class="bg-[var(--ink)] text-white">
    <div class="section text-center"><h2 class="display-serif mx-auto max-w-3xl text-4xl leading-[1.15] md:text-5xl">The product creates the response.<br>The guided experience helps make it readable.</h2><div class="mx-auto mt-9 grid max-w-3xl gap-4 text-left md:grid-cols-2"><div class="rounded-lg border border-white/15 bg-white/5 p-6"><div class="text-[11px] font-medium uppercase tracking-[.16em] text-white/70">The Product</div><ul class="mt-4 space-y-1.5 text-[13px] leading-6 text-white/85"><li>· Targeted daily product</li><li>· 30 days of support</li><li>· One daily moment</li></ul></div><div class="rounded-lg border border-white/15 bg-white/5 p-6"><div class="text-[11px] font-medium uppercase tracking-[.16em] text-white/70">The Guided Layer</div><ul class="mt-4 space-y-1.5 text-[13px] leading-6 text-white/85"><li>· Starting point</li><li>· Course moments</li><li>· Gut Response Brief</li></ul></div></div></div>
</section>

<section class="section"><h2 class="display-serif text-center text-4xl leading-tight md:text-5xl">A 30-Day Guided Journey</h2><div class="mt-12 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">@foreach([['Before Day 1','Starting Point'],['Day 3','Product Fit'],['Day 7','First-Week Signal'],['Day 14','Midpoint Pattern'],['Day 21','Final Stretch'],['Day 30','Gut Response Brief']] as [$day, $label])<article class="rounded-lg border border-stone-200 bg-white p-4 text-center"><div class="mx-auto grid h-8 w-8 place-items-center rounded-full bg-[var(--cream)] text-[var(--ink)]">•</div><div class="mt-3 text-[11px] font-medium uppercase tracking-[.14em] text-stone-500">{{ $day }}</div><h3 class="display-serif mt-1 text-lg leading-snug">{{ $label }}</h3></article>@endforeach</div><div class="mx-auto mt-10 max-w-md rounded-lg border border-stone-200 bg-[var(--cream)] p-4 text-center text-[13px] text-stone-600">15 minutes total · 6 milestones</div></section>

<section class="bg-[var(--cream)]/70"><div class="section"><h2 class="display-serif text-4xl leading-tight md:text-5xl">Designed to fit real life.</h2><p class="mt-4 max-w-2xl text-[14px] leading-7 text-stone-600">A gentle guided layer, sensitive to the ways real life interrupts.</p><div class="mt-8 grid gap-4 md:grid-cols-4">@foreach([['Life Load','Real-life demands are recorded as context, not failure.'],['Credibility','Every observation is stored honestly.'],['Add Context','A few short moments capture what matters.'],['Return Ready','Return to your course at any time via your product access.']] as [$title, $copy])<article class="rounded-lg bg-white p-5"><h3 class="display-serif text-xl">{{ $title }}</h3><p class="mt-2 text-[12px] leading-6 text-stone-600">{{ $copy }}</p></article>@endforeach</div></div></section>

<section class="section"><h2 class="display-serif text-center text-4xl leading-tight md:text-5xl">A missed day does not erase the journey.</h2><div class="mx-auto mt-10 grid max-w-4xl gap-4 md:grid-cols-2">@foreach([['Missed Product','Recorded, then continued.'],['Travel or Diet Change','Captured as context.'],['Missed Milestone','Return to it. The milestone waits.'],['Uneven Feeling','Add a short note if it helps.']] as [$title, $copy])<article class="rounded-lg border border-stone-200 bg-white p-5"><h3 class="display-serif text-xl">{{ $title }}</h3><p class="mt-2 text-[13px] text-stone-600">{{ $copy }}</p></article>@endforeach</div></section>

<section class="bg-[var(--ink)] text-white"><div class="section"><h2 class="display-serif text-4xl leading-tight md:text-5xl">Built for an honest read.</h2><ul class="mt-8 max-w-2xl space-y-4 text-[14px] leading-6 text-white/85"><li>· Anchoring on your starting intention.</li><li>· Separating routine disruptions from response signals.</li><li>· Weighing product exposure against reported response.</li><li>· Preserving observations, not conclusions.</li><li>· Offering the most relevant next step, not a score.</li></ul></div></section>

<section class="section grid items-center gap-10 lg:grid-cols-2 lg:gap-16"><div class="overflow-hidden rounded-xl bg-[var(--cream)]"><img src="https://guided-gut-reset-lovable-app.lovable.app/assets/bottle-capsules-COsDFlLa.jpg" alt="Sample Gut Response Brief" class="aspect-[4/3] h-full w-full object-cover"></div><div><h2 class="display-serif text-4xl leading-tight md:text-5xl">Your personal Gut Response Brief.</h2><p class="mt-5 max-w-md text-[14px] leading-7 text-stone-600">A single honest read of the 30 days: what changed, what did not, the context around it, and the most relevant next step.</p><div class="mt-6 flex flex-wrap gap-2">@foreach(['Repeat','Maintenance','Try another','Stop','Doctor first'] as $outcome)<span class="rounded-full border border-stone-200 px-3 py-1 text-[11px]">{{ $outcome }}</span>@endforeach</div></div></section>

<section class="bg-[var(--cream)]/70"><div class="section grid items-center gap-10 lg:grid-cols-2 lg:gap-16"><div class="overflow-hidden rounded-xl bg-white"><img src="https://guided-gut-reset-lovable-app.lovable.app/assets/course-kit-DtVPc2tT.jpg" alt="Guided Wellness course kit" class="aspect-[4/3] h-full w-full object-cover"></div><div><h2 class="display-serif text-4xl leading-tight md:text-5xl">The physical pack helps you start correctly.</h2><ul class="mt-6 space-y-2 text-[13px] leading-6 text-stone-600"><li>· Product-attached start cue</li><li>· Course Companion card</li><li>· Welcome Guide</li></ul></div></div></section>

<section class="section"><div class="grid gap-10 lg:grid-cols-[1fr_1.5fr]"><div><h2 class="display-serif text-4xl leading-tight md:text-5xl">Help is available when you need it.</h2><a href="{{ url('/#faq') }}" class="btn-secondary mt-6">Contact Us</a></div><div class="grid gap-4 sm:grid-cols-2">@foreach([['WhatsApp','Ask a question or share a concern.'],['Email','Reach us for account or product help.'],['Guidance','Speak to a doctor first if unsure.'],['Support','See our support page for common questions.']] as [$title, $copy])<article class="rounded-lg border border-stone-200 bg-white p-5"><h3 class="display-serif text-xl">{{ $title }}</h3><p class="mt-2 text-[12px] leading-6 text-stone-600">{{ $copy }}</p></article>@endforeach</div></div></section>

<section class="border-t border-stone-200 bg-[var(--cream)]/45"><div class="section grid gap-10 md:grid-cols-2"><div><div class="badge">Ready if relevant</div><ul class="mt-4 space-y-1.5 text-[13px] leading-6 text-stone-600"><li>· Recurring gut discomfort</li><li>· Looking for structure</li><li>· Want to observe response</li></ul></div><div><div class="badge">Speak to a doctor first</div><ul class="mt-4 space-y-1.5 text-[13px] leading-6 text-stone-600"><li>· Pregnant or breast-feeding</li><li>· Diagnosed condition</li><li>· On prescription medication</li></ul></div></div></section>

<section class="bg-[var(--ink)] text-center text-white"><div class="section py-16"><h2 class="display-serif text-4xl leading-tight md:text-5xl">Give the product a fair 30-day trial.</h2><div class="mt-7 flex flex-wrap justify-center gap-3"><a href="{{ route('shop') }}" class="btn-primary !bg-white !text-[var(--ink)]">Shop</a><a href="{{ url('/#fit') }}" class="btn-secondary !border-white/30 !text-white hover:!bg-white/10">Check Fit</a></div></div></section>
@endsection
