<?php $__env->startSection('content'); ?>
<div class="p-6 md:p-10"><div><span class="badge">Programme operations</span><h1 class="serif mt-3 text-4xl">Day 0–30 operations</h1></div>
<div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><?php $__currentLoopData = [['Active',$active],['Completed',$completed],['Day 0',$day0],['Day 30',$day30],['Safety flags',$safety_flags],['Manual review',$manual_review]]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $x): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="card"><div class="text-xs uppercase text-stone-500"><?php echo e($x[0]); ?></div><div class="mt-2 text-2xl font-bold"><?php echo e($x[1]); ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
<div class="mt-6 grid gap-6 lg:grid-cols-2"><div class="card"><h2 class="font-bold">Today</h2><div class="mt-5 grid grid-cols-3 gap-3 text-center"><div><div class="text-2xl font-bold"><?php echo e($today_total); ?></div><div class="text-xs text-stone-500">Scheduled</div></div><div><div class="text-2xl font-bold"><?php echo e($today_responded); ?></div><div class="text-xs text-stone-500">Responded</div></div><div><div class="text-2xl font-bold"><?php echo e($today_completed); ?></div><div class="text-xs text-stone-500">Completed</div></div></div><div class="mt-6 text-sm">Response rate <b><?php echo e($today_response_rate); ?>%</b> · Completion rate <b><?php echo e($today_completion_rate); ?>%</b></div></div>
<div class="card"><h2 class="font-bold">Milestones</h2><div class="mt-5 space-y-3"><?php $__currentLoopData = $milestones; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $k=>$v): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="flex justify-between border-b pb-3"><span><?php echo e(ucfirst($k)); ?></span><b><?php echo e($v); ?></b></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></div></div>
<div class="card mt-6"><h2 class="font-bold">Active customers by reset day</h2><div class="mt-5 flex flex-wrap gap-2"><?php $__empty_1 = true; $__currentLoopData = $day_distribution; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $d): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><span class="rounded-full bg-stone-100 px-4 py-2 text-sm">Day <?php echo e($d->current_reset_day); ?> · <?php echo e($d->total); ?></span><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="text-stone-500">No active reset profiles.</p><?php endif; ?></div></div>
<div class="card mt-6 overflow-x-auto"><h2 class="font-bold">Recent reset profiles</h2><table class="mt-5 w-full text-sm"><thead><tr class="border-b text-left"><th class="p-2">Customer</th><th class="p-2">Day</th><th class="p-2">Status</th><th class="p-2">Safety</th><th class="p-2">Review</th></tr></thead><tbody><?php $__currentLoopData = $recent; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $p): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr class="border-b"><td class="p-2"><?php echo e($p->user?->name ?: $p->user?->email); ?></td><td class="p-2"><?php echo e($p->current_reset_day); ?></td><td class="p-2"><?php echo e($p->status); ?></td><td class="p-2"><?php echo e($p->safety_flag_active?'Yes':'No'); ?></td><td class="p-2"><?php echo e($p->manual_review_required?'Yes':'No'); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\gutreset\resources\views/admin/reset/index.blade.php ENDPATH**/ ?>