<?php $__env->startSection('content'); ?>
<div class="p-6 md:p-10 max-w-6xl"><a class="underline text-sm" href="<?php echo e(route('admin.orders.index')); ?>">← Orders</a><h1 class="serif mt-4 text-4xl"><?php echo e($order->order_number); ?></h1>
<div class="mt-8 grid gap-6 lg:grid-cols-3">
<div class="card lg:col-span-2"><h2 class="font-bold">Items</h2><div class="mt-5 space-y-4"><?php $__currentLoopData = $order->orderItems; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $i): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="flex justify-between border-b pb-3"><span><?php echo e($i->product_name_snapshot); ?> × <?php echo e($i->quantity); ?></span><span>₹<?php echo e(number_format($i->line_total,2)); ?></span></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><div class="mt-5 text-right text-xl font-bold">₹<?php echo e(number_format($order->grand_total,2)); ?></div></div>
<div class="card"><h2 class="font-bold">Update lifecycle</h2><form method="POST" action="<?php echo e(route('admin.orders.update',$order)); ?>" class="mt-5 space-y-4"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?>
<?php $__currentLoopData = ['payment_status'=>'Payment','fulfilment_status'=>'Fulfilment','shipment_status'=>'Shipment']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $field=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div><label class="text-sm"><?php echo e($label); ?></label><select name="<?php echo e($field); ?>" class="mt-2 w-full rounded-xl border p-3"><?php $__currentLoopData = ['pending','paid','failed','processing','packed','dispatched','delivered','cancelled','refunded']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $s): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($s); ?>" <?php if($order->$field===$s): echo 'selected'; endif; ?>><?php echo e($s); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
<button class="btn-primary w-full">Save status</button></form></div></div>
<div class="card mt-6"><h2 class="font-bold">Shipping address</h2><pre class="mt-4 whitespace-pre-wrap text-sm"><?php echo e(json_encode($order->shipping_address_json,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)); ?></pre></div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp83\htdocs\gutreset\resources\views\admin\orders\show.blade.php ENDPATH**/ ?>