<?php $__env->startSection('content'); ?>
<div class="p-6 md:p-10"><a class="text-sm underline" href="<?php echo e(route('admin.payments.index')); ?>">← Payments</a><h1 class="serif mt-4 text-4xl">Payment #<?php echo e($payment->id); ?></h1>
<?php if(session('success')): ?><div class="mt-5 rounded-xl bg-green-50 p-4 text-green-800"><?php echo e(session('success')); ?></div><?php endif; ?>
<?php if(session('error')): ?><div class="mt-5 rounded-xl bg-red-50 p-4 text-red-800"><?php echo e(session('error')); ?></div><?php endif; ?>
<div class="mt-8 grid gap-5 lg:grid-cols-3"><div class="card"><div class="text-sm text-stone-500">Order</div><div class="mt-2 font-bold"><?php echo e($payment->order?->order_number); ?></div></div><div class="card"><div class="text-sm text-stone-500">Amount</div><div class="mt-2 font-bold">₹<?php echo e(number_format($payment->amount,2)); ?></div></div><div class="card"><div class="text-sm text-stone-500">Status</div><div class="mt-2 font-bold"><?php echo e($payment->status); ?></div></div></div>
<div class="mt-6 grid gap-6 lg:grid-cols-2"><div class="card"><h2 class="font-bold">Gateway</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between"><dt>Gateway</dt><dd><?php echo e($payment->gateway); ?></dd></div><div class="flex justify-between"><dt>Gateway order</dt><dd><?php echo e($payment->gateway_order_id ?: '—'); ?></dd></div><div class="flex justify-between"><dt>Idempotency</dt><dd><?php echo e($payment->idempotency_key); ?></dd></div><div class="flex justify-between"><dt>Paid at</dt><dd><?php echo e($payment->paid_at?->format('d M Y H:i') ?: '—'); ?></dd></div></dl><?php if(in_array($payment->status,['pending','authorized'])): ?><form method="POST" action="<?php echo e(route('admin.payments.reconcile',$payment)); ?>" class="mt-6"><?php echo csrf_field(); ?><button class="btn-primary w-full">Reconcile now</button></form><?php endif; ?></div>
<div class="card"><h2 class="font-bold">Transaction history</h2><div class="mt-4 space-y-4"><?php $__empty_1 = true; $__currentLoopData = $payment->transactions->sortByDesc('id'); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $t): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="border-b pb-3 text-sm"><div class="flex justify-between font-semibold"><span><?php echo e($t->transaction_type); ?></span><span><?php echo e($t->gateway_status); ?></span></div><div class="mt-1 text-stone-500"><?php echo e($t->processed_at?->format('d M Y H:i:s')); ?> · ₹<?php echo e(number_format($t->amount,2)); ?></div><div class="mt-1 text-xs">Signature verified: <?php echo e($t->signature_verified ? 'Yes':'No'); ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="text-stone-500">No transactions.</p><?php endif; ?></div></div></div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp83\htdocs\gutreset\resources\views\admin\payments\show.blade.php ENDPATH**/ ?>