<?php $__env->startSection('content'); ?>
<div class="p-6 md:p-10"><span class="badge">Configuration</span><h1 class="serif mt-3 text-4xl">Shipping methods & rates</h1>
<?php if(session('success')): ?><div class="mt-5 rounded-xl bg-green-50 p-4 text-green-800"><?php echo e(session('success')); ?></div><?php endif; ?>
<div class="mt-8 grid gap-6 lg:grid-cols-3">
<div class="card"><h2 class="font-bold">Add method</h2><form method="POST" action="<?php echo e(route('admin.shipping.store')); ?>" class="mt-4 space-y-3"><?php echo csrf_field(); ?><input name="name" required placeholder="Name" class="w-full rounded-xl border p-3"><input name="code" required placeholder="Code" class="w-full rounded-xl border p-3"><input name="courier" placeholder="Courier" class="w-full rounded-xl border p-3"><div class="grid grid-cols-2 gap-3"><input name="estimated_min_days" placeholder="Min days" class="rounded-xl border p-3"><input name="estimated_max_days" placeholder="Max days" class="rounded-xl border p-3"></div><button class="btn-primary w-full">Add</button></form></div>
<div class="lg:col-span-2 space-y-4"><?php $__currentLoopData = $methods; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $m): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="card"><div class="flex justify-between"><div><b><?php echo e($m->name); ?></b> <span class="text-xs text-stone-500"><?php echo e($m->code); ?></span></div><span><?php echo e($m->estimated_min_days); ?>–<?php echo e($m->estimated_max_days); ?> days</span></div><div class="mt-4 space-y-2"><?php $__currentLoopData = $m->rates; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $r): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="flex justify-between text-sm rounded-xl bg-stone-50 p-3"><span><?php echo e($r->country); ?> <?php echo e($r->state); ?> <?php echo e($r->postal_code_prefix); ?></span><span><?php echo e($r->free_shipping?'Free':'₹'.number_format($r->shipping_charge,2)); ?></span></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
</div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\gutreset\resources\views/admin/shipping/index.blade.php ENDPATH**/ ?>