<?php $__env->startSection('content'); ?>
<div class="p-6 md:p-10"><div><span class="badge">Operations</span><h1 class="serif mt-3 text-4xl">Shipment & fulfilment</h1></div>
<div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><?php $__currentLoopData = [['Pending',$totals['pending']],['Packed',$totals['packed']],['In transit',$totals['in_transit']],['Out for delivery',$totals['out_for_delivery']],['Delivered',$totals['delivered']]]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $x): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="card"><div class="text-xs uppercase text-stone-500"><?php echo e($x[0]); ?></div><div class="mt-2 text-2xl font-bold"><?php echo e($x[1]); ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
<div class="card mt-8 overflow-x-auto"><form class="mb-5 flex gap-2"><select name="status" class="rounded-xl border p-2"><option value="">All statuses</option><?php $__currentLoopData = ['pending','created','packed','dispatched','in_transit','out_for_delivery','delivered']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $s): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option <?php if(request('status')===$s): echo 'selected'; endif; ?>><?php echo e($s); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><button class="rounded-xl bg-stone-200 px-4 py-2">Filter</button></form>
<table class="w-full text-sm"><thead><tr class="border-b text-left"><th class="p-3">Shipment</th><th class="p-3">Order</th><th class="p-3">Customer</th><th class="p-3">Courier</th><th class="p-3">Tracking</th><th class="p-3">Status</th><th class="p-3">Expected</th><th class="p-3">Action</th></tr></thead><tbody>
<?php $__currentLoopData = $shipments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $s): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr class="border-b"><td class="p-3"><?php echo e($s->shipment_number); ?></td><td class="p-3"><?php echo e($s->order?->order_number); ?></td><td class="p-3"><?php echo e($s->order?->user?->name ?: $s->order?->user?->email); ?></td><td class="p-3"><?php echo e($s->courier ?: '—'); ?></td><td class="p-3"><?php echo e($s->tracking_number ?: '—'); ?></td><td class="p-3"><?php echo e($s->status); ?></td><td class="p-3"><?php echo e($s->expected_delivery?->format('d M Y') ?: '—'); ?></td><td class="p-3"><form method="POST" action="<?php echo e(route('admin.fulfilment.update',$s)); ?>" class="flex gap-2"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?><input type="hidden" name="status" value="<?php echo e($s->status); ?>"><input name="tracking_number" value="<?php echo e($s->tracking_number); ?>" placeholder="Tracking" class="w-28 rounded border p-1"><button class="rounded bg-stone-200 px-2">Save</button></form></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
</tbody></table><div class="mt-5"><?php echo e($shipments->links()); ?></div></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\gutreset\resources\views/admin/fulfilment/index.blade.php ENDPATH**/ ?>