<?php $__env->startSection('content'); ?>
<div class="p-6 md:p-10">
<div class="flex flex-wrap items-end justify-between gap-4"><div><span class="badge">Finance</span><h1 class="serif mt-3 text-4xl">Payments & reconciliation</h1></div><a class="rounded-xl bg-stone-900 px-4 py-3 text-sm font-semibold text-white" href="<?php echo e(route('admin.dashboard')); ?>">Dashboard</a></div>
<div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-6">
<?php $__currentLoopData = [['All',$totals['all']],['Paid',$totals['paid']],['Pending',$totals['pending']],['Failed',$totals['failed']],['Paid value','₹'.number_format($totals['paid_amount'],2)],['Pending value','₹'.number_format($totals['pending_amount'],2)]]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $x): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="card"><div class="text-xs uppercase tracking-wide text-stone-500"><?php echo e($x[0]); ?></div><div class="mt-2 text-xl font-bold"><?php echo e($x[1]); ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
</div>
<div class="card mt-8 overflow-x-auto"><form class="mb-5 flex flex-wrap gap-2"><select name="status" class="rounded-xl border p-2"><option value="">All status</option><?php $__currentLoopData = ['pending','authorized','paid','failed']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $s): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option <?php if(request('status')===$s): echo 'selected'; endif; ?>><?php echo e($s); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><select name="gateway" class="rounded-xl border p-2"><option value="">All gateways</option><option value="razorpay" <?php if(request('gateway')==='razorpay'): echo 'selected'; endif; ?>>Razorpay</option></select><button class="rounded-xl bg-stone-200 px-4 py-2">Filter</button></form>
<table class="w-full text-sm"><thead><tr class="border-b text-left"><th class="p-3">Payment</th><th class="p-3">Order</th><th class="p-3">Customer</th><th class="p-3">Gateway</th><th class="p-3">Amount</th><th class="p-3">Status</th><th class="p-3"></th></tr></thead><tbody>
<?php $__currentLoopData = $payments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $p): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr class="border-b"><td class="p-3">#<?php echo e($p->id); ?></td><td class="p-3"><?php echo e($p->order?->order_number); ?></td><td class="p-3"><?php echo e($p->order?->user?->name ?: $p->order?->user?->email); ?></td><td class="p-3"><?php echo e($p->gateway); ?></td><td class="p-3">₹<?php echo e(number_format($p->amount,2)); ?></td><td class="p-3"><span class="rounded-full bg-stone-100 px-2 py-1"><?php echo e($p->status); ?></span></td><td class="p-3"><a class="underline" href="<?php echo e(route('admin.payments.show',$p)); ?>">View</a></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
</tbody></table><div class="mt-5"><?php echo e($payments->links()); ?></div></div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\gutreset\resources\views/admin/payments/index.blade.php ENDPATH**/ ?>