@extends('layouts.admin')
@section('content')
<div class="p-6 md:p-10"><div><span class="badge">Operations</span><h1 class="serif mt-3 text-4xl">Shipment & fulfilment</h1></div>
<div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">@foreach([['Pending',$totals['pending']],['Packed',$totals['packed']],['In transit',$totals['in_transit']],['Out for delivery',$totals['out_for_delivery']],['Delivered',$totals['delivered']]] as $x)<div class="card"><div class="text-xs uppercase text-stone-500">{{ $x[0] }}</div><div class="mt-2 text-2xl font-bold">{{ $x[1] }}</div></div>@endforeach</div>
<div class="card mt-8 overflow-x-auto"><form class="mb-5 flex gap-2"><select name="status" class="rounded-xl border p-2"><option value="">All statuses</option>@foreach(['pending','created','packed','dispatched','in_transit','out_for_delivery','delivered'] as $s)<option @selected(request('status')===$s)>{{ $s }}</option>@endforeach</select><button class="rounded-xl bg-stone-200 px-4 py-2">Filter</button></form>
<table class="w-full text-sm"><thead><tr class="border-b text-left"><th class="p-3">Shipment</th><th class="p-3">Order</th><th class="p-3">Customer</th><th class="p-3">Courier</th><th class="p-3">Tracking</th><th class="p-3">Status</th><th class="p-3">Expected</th><th class="p-3">Action</th></tr></thead><tbody>
@foreach($shipments as $s)<tr class="border-b"><td class="p-3">{{ $s->shipment_number }}</td><td class="p-3">{{ $s->order?->order_number }}</td><td class="p-3">{{ $s->order?->user?->name ?: $s->order?->user?->email }}</td><td class="p-3">{{ $s->courier ?: '—' }}</td><td class="p-3">{{ $s->tracking_number ?: '—' }}</td><td class="p-3">{{ $s->status }}</td><td class="p-3">{{ $s->expected_delivery?->format('d M Y') ?: '—' }}</td><td class="p-3"><form method="POST" action="{{ route('admin.fulfilment.update',$s) }}" class="flex gap-2">@csrf @method('PUT')<input type="hidden" name="status" value="{{ $s->status }}"><input name="tracking_number" value="{{ $s->tracking_number }}" placeholder="Tracking" class="w-28 rounded border p-1"><button class="rounded bg-stone-200 px-2">Save</button></form></td></tr>@endforeach
</tbody></table><div class="mt-5">{{ $shipments->links() }}</div></div></div>
@endsection
