@extends('layouts.admin')
@section('content')
<div class="p-6 md:p-10"><a class="text-sm underline" href="{{ route('admin.payments.index') }}">← Payments</a><h1 class="serif mt-4 text-4xl">Payment #{{ $payment->id }}</h1>
@if(session('success'))<div class="mt-5 rounded-xl bg-green-50 p-4 text-green-800">{{ session('success') }}</div>@endif
@if(session('error'))<div class="mt-5 rounded-xl bg-red-50 p-4 text-red-800">{{ session('error') }}</div>@endif
<div class="mt-8 grid gap-5 lg:grid-cols-3"><div class="card"><div class="text-sm text-stone-500">Order</div><div class="mt-2 font-bold">{{ $payment->order?->order_number }}</div></div><div class="card"><div class="text-sm text-stone-500">Amount</div><div class="mt-2 font-bold">₹{{ number_format($payment->amount,2) }}</div></div><div class="card"><div class="text-sm text-stone-500">Status</div><div class="mt-2 font-bold">{{ $payment->status }}</div></div></div>
<div class="mt-6 grid gap-6 lg:grid-cols-2"><div class="card"><h2 class="font-bold">Gateway</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between"><dt>Gateway</dt><dd>{{ $payment->gateway }}</dd></div><div class="flex justify-between"><dt>Gateway order</dt><dd>{{ $payment->gateway_order_id ?: '—' }}</dd></div><div class="flex justify-between"><dt>Idempotency</dt><dd>{{ $payment->idempotency_key }}</dd></div><div class="flex justify-between"><dt>Paid at</dt><dd>{{ $payment->paid_at?->format('d M Y H:i') ?: '—' }}</dd></div></dl>@if(in_array($payment->status,['pending','authorized']))<form method="POST" action="{{ route('admin.payments.reconcile',$payment) }}" class="mt-6">@csrf<button class="btn-primary w-full">Reconcile now</button></form>@endif</div>
<div class="card"><h2 class="font-bold">Transaction history</h2><div class="mt-4 space-y-4">@forelse($payment->transactions->sortByDesc('id') as $t)<div class="border-b pb-3 text-sm"><div class="flex justify-between font-semibold"><span>{{ $t->transaction_type }}</span><span>{{ $t->gateway_status }}</span></div><div class="mt-1 text-stone-500">{{ $t->processed_at?->format('d M Y H:i:s') }} · ₹{{ number_format($t->amount,2) }}</div><div class="mt-1 text-xs">Signature verified: {{ $t->signature_verified ? 'Yes':'No' }}</div></div>@empty<p class="text-stone-500">No transactions.</p>@endforelse</div></div></div>
</div>
@endsection
