@extends('layouts.admin')
@section('content')
<div class="p-6 md:p-10"><div class="flex flex-wrap items-end justify-between gap-4"><div><span class="badge">Programme operations</span><h1 class="serif mt-3 text-4xl">Day 0–30 operations</h1><p class="mt-2 text-sm text-stone-500">Track active cycles, safety holds, drop-offs, final briefs and re-entry approvals.</p></div><div class="flex flex-wrap gap-2"><a class="btn-secondary" href="{{ route('admin.reset.reentry') }}">Re-entry</a><a class="btn-secondary" href="{{ route('admin.reset.testimonials') }}">Testimonials</a></div></div>
<div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-6">@foreach([['Active',$active],['Completed',$completed],['Day 0',$day0],['Day 30',$day30],['Drop-offs',$dropoffs],['Paused',$paused],['Safety review',$safety_flags],['Manual review',$manual_review],['Re-entry pending',$reentry_pending],['Testimonials pending',$testimonials_pending]] as $x)<div class="card"><div class="text-xs uppercase text-stone-500">{{ $x[0] }}</div><div class="mt-2 text-2xl font-bold">{{ $x[1] }}</div></div>@endforeach</div>
<div class="mt-6 grid gap-6 lg:grid-cols-2"><div class="card"><h2 class="font-bold">Today</h2><div class="mt-5 grid grid-cols-3 gap-3 text-center"><div><div class="text-2xl font-bold">{{ $today_total }}</div><div class="text-xs text-stone-500">Scheduled</div></div><div><div class="text-2xl font-bold">{{ $today_responded }}</div><div class="text-xs text-stone-500">Responded</div></div><div><div class="text-2xl font-bold">{{ $today_completed }}</div><div class="text-xs text-stone-500">Completed</div></div></div><div class="mt-6 text-sm">Response rate <b>{{ $today_response_rate }}%</b> · Completion rate <b>{{ $today_completion_rate }}%</b></div></div>
<div class="card"><h2 class="font-bold">Milestones</h2><div class="mt-5 space-y-3">@foreach($milestones as $k=>$v)<div class="flex justify-between border-b pb-3"><span>{{ ucfirst($k) }}</span><b>{{ $v }}</b></div>@endforeach</div></div></div>
<div class="card mt-6"><h2 class="font-bold">Active customers by reset day</h2><div class="mt-5 flex flex-wrap gap-2">@forelse($day_distribution as $d)<span class="rounded-full bg-stone-100 px-4 py-2 text-sm">Day {{ $d->current_reset_day }} · {{ $d->total }}</span>@empty<p class="text-stone-500">No active reset profiles.</p>@endforelse</div></div>
<div class="card mt-6 overflow-x-auto"><h2 class="font-bold">Recent reset profiles</h2><table class="mt-5 w-full text-sm"><thead><tr class="border-b text-left"><th class="p-2">Customer</th><th class="p-2">Day</th><th class="p-2">Status</th><th class="p-2">Safety</th><th class="p-2">Review</th></tr></thead><tbody>@foreach($recent as $p)<tr class="border-b"><td class="p-2"><a class="font-semibold underline" href="{{ route('admin.reset.profiles.show',$p) }}">{{ $p->user?->name ?: $p->user?->email }}</a><div class="text-xs text-stone-500">Cycle #{{ $p->cycle_number }}</div></td><td class="p-2">{{ $p->current_reset_day }}</td><td class="p-2">{{ $p->status }}</td><td class="p-2">{{ $p->safety_flag_active?'Yes':'No' }}</td><td class="p-2">{{ $p->manual_review_required?'Yes':'No' }}</td></tr>@endforeach</tbody></table></div>
</div>
@endsection
